name: main

on:
  push:
    branches:
      - main  #uruchomienie przy push na main

jobs:
  main:
    runs-on: ${{ matrix.os }} #wybór systemu wg matrixa

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]  #systemy windows i ubuntu
        python-version: [3.9, "3.10", "3.11"]  #wersje pythona
      exclude:
        - os: ubuntu-latest
          python-version: "3.10"  #wyjątek wersji 3.10 dla Ubuntu

    steps:
      - name: Set up Python  #konfigruracja środowiska 
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip  #aktualizacja pip
        run: |
          python -m pip install --upgrade pip
          
      - name: Display Python version  #wyświetlenie wersji Pythona
        run: |
          python --version

      - name: Run flake8  #uruchomienie flake8
        run: |
          flake8 .

      - name: Run unittest  #uruchomienie testów z użyciem unittest
        run: |
          python -m unittest discover -v
